Add Xbox Support for Java
wpilibsuite/RobotBuilder pull request #271
Opened 2020-10-25 02:22 UTC by cpapplefamily

This has all the edits required to add Xbox Controller and Xbox buttons to the menus and output Java code. Also Allows for future "Joystick" type Extensions to be created.

2020-10-26 23:39 UTC, sciencewhiz commented
Can you rebase this on master? It doesn't change cleanly if I change the PR to master.

2020-10-27 20:22 UTC, cpapplefamily commented
> Can you rebase this on master? It doesn't change cleanly if I change the PR to master.

Is that simply using the following while on my branch?
`git pull --rebase upstream master`

Then push to my online repo

2020-10-28 01:40 UTC, sciencewhiz commented
Yes. You will get merge conflicts with some of the duplicate commits that you will need to skip. You will also need to force push to your branch.

2020-10-28 03:00 UTC, sciencewhiz requested changes

2020-10-28 03:00 UTC, sciencewhiz commented on src/main/resources/help/Xbox Controller.html
> +            alt="Joystick" />
```suggestion
            alt="Xbox Controller" />
```

2020-10-28 03:07 UTC, sciencewhiz commented
Use the Joystick Button html from #234 as a basis

2020-10-28 12:46 UTC, cpapplefamily commented
> Yes. You will get merge conflicts with some of the duplicate commits that you will need to skip. You will also need to force push to your branch.

I only see the one conflict Should I select Accept Incoming? 
![Capture](https://user-images.githubusercontent.com/16618289/97437461-66890800-191b-11eb-8d5f-b56d4ac6a19c.PNG)

2020-10-28 19:36 UTC, sciencewhiz commented
You want to accept current change for that one. I suspect once you clear that one, there will be more.

2020-10-28 23:43 UTC, cpapplefamily commented
> Yes. You will get merge conflicts with some of the duplicate commits that you will need to skip. You will also need to force push to your branch.

@sciencewhiz 
Is this supposed to be a pain in the backside? I have tried to suffer through and honestly would have been easier to create a new branch and re-apply my edits. I would love to watch the process if someone wanted to screen share.

2020-10-29 00:08 UTC, cpapplefamily commented
Commit two after the first time I `git rebase --continue`
My steps

1. Check out Xbox-Controller-Java-Support
2. `git pull --rebase origin master`  (*origin is equal to upstream now)
3. Fix conflict or `accept current change`
4.  `git add src/main/java/robotbuilder/exporters/GenericExporter.java`
5. `git rebase --continue` This is where it goes south and all my attempts usually end here:

```
E325: ATTENTION
Found a swap file by the name "C:/Users/Robotics/FRCProjects 2021/WPILIB_RobotBuilder/RobotBuilder/.git/.COMMIT_EDITMSG.swp"
          owned by: Robotics   dated: Wed Oct 28 08:23:57 2020
         file name: ~Robotics/FRCProjects 2021/WPILIB_RobotBuilder/RobotBuilder/.git/COMMIT_EDITMSG
          modified: no
         user name: Robotics   host name: Robotics-PC
        process ID: 184 (STILL RUNNING)
While opening file "C:/Users/Robotics/FRCProjects 2021/WPILIB_RobotBuilder/RobotBuilder/.git/COMMIT_EDITMSG"
             dated: Wed Oct 28 18:50:07 2020
      NEWER than swap file!

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r C:/Users/Robotics/FRCProjects 2021/WPILIB_RobotBuilder/RobotBuilder/.git/COMMIT_EDITMSG"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "C:/Users/Robotics/FRCProjects 2021/WPILIB_RobotBuilder/RobotBuilder/.git/.COMMIT_EDITMSG.swp"
    to avoid this message.

Swap file "C:/Users/Robotics/FRCProjects 2021/WPILIB_RobotBuilder/RobotBuilder/.git/.COMMIT_EDITMSG.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (Q)uit, (A)bort: 
```

2020-10-31 04:11 UTC, sciencewhiz commented
I'm not sure why you're getting vim swap file errors, unless its the combination of vs code and git commandline.

cherry-picking on a clean branch is also an option.

2020-10-31 17:00 UTC, cpapplefamily commented
Maybe Ill try to use the Git-SVN outside VSCode

2020-10-31 23:15 UTC, cpapplefamily commented
@sciencewhiz I either 100% was successful or not. It the rebase is not correct I will delete my branch and start a new one off the current Master. Do I need to change the into branch? because you had me rebase to the master.

2020-10-31 23:27 UTC, sciencewhiz commented
After changing the PR base branch to master, it looks much better. However, it looks like there's unitentional changes to command.java.

2020-11-01 04:11 UTC, cpapplefamily commented
I recall that one giving me some trouble. If that's all then great and I'll be a bit more careful on the next one.

2020-11-09 03:08 UTC, sciencewhiz commented on src/main/resources/export/java/macros.vm
> +#macro( type2 $component )$component.getBase().getType()#end
I would prefer a more descriptive name, like base_type

2020-11-09 03:58 UTC, cpapplefamily commented
Sure I get it. That was obviously a test macro to attempt to get the correct data and not break other calls to it. As a follow-up should 
`#macro( type $component )${helper.getInstruction($component, "ClassName")}#end`
Get refactored to something that is more representative to get_class? Probably more involved and worthy of a new issue tracker.

2020-11-11 00:59 UTC, sciencewhiz commented
I think type is fine as the class is the type

2020-11-11 02:10 UTC, cpapplefamily commented
Suggested change complete

2020-12-19 19:57 UTC, sciencewhiz commented
superseded by #335

2020-12-19 19:57 UTC, closed without merging